env:
  browser: false
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 8
rules:
  indent:
    - off
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console:
    - off
  no-cond-assign:
    - off
